### ISSUE TITLE
Failed to open device, no matching device could be found opened.

### ISSUE THREAD

**Issue by JoeyLeeNPU** [uzh-rpg/rpg_dvs_ros#104]
Hi,

I have installed DVS_ros driver according to Readme.txt, but when I run "roslaunch dvs_renderer dvs_mono.launch", terminal shows that "failed to open device, no matching device could be found opened. "

Thanks,
Joey

**Comment by llongi** [comment]
That means the DVS128 device cannot be accessed on your system. This is usually because the Linux udev-rules file from libcaer is missing or not installed properly, or because the particular user you are running ROS as doesn't have sufficient permissions.
Try installing the official libcaer (see README), and reboot your system so that the udev changes take effect.
