### ISSUE TITLE
Autoexposure issue with DAVIS346

### ISSUE THREAD

**Issue by ahadviger** [uzh-rpg/rpg_dvs_ros#105]
Hello,

I was using `dvs_renderer` to record ROS bags with a DAVIS346 device. Autoexposure was enabled by setting `autoexposure_enabled: true` in the configuration .yaml file. At first everything seemed to work fine, but then exposure started to oscillate between two values and never recovered. Is there anything that can be done to avoid this?

Thank you,
Antea

**Comment by llongi** [comment]
Just for info, the DAVIS ROS driver uses its own implementation of auto-exposure, distinct from the libcaer one, code here:
https://github.com/uzh-rpg/rpg_dvs_ros/blob/master/davis_ros_driver/src/driver.cpp#L857
Looks like both suffer from potential oscillations in edge cases due to relatively simple control loops.
